### ISSUE TITLE
Yank key is not working on Neovim nigthly

### ISSUE THREAD

**Issue by mosheavni** [cuducos/yaml.nvim#21] opened 2023-04-05 15:19 UTC
when running `:YAMLYankKey` I get:

```
2023-04-05T11:17:20  WARN vim.treesitter.query.get_node_text() is deprecated, use vim.treesitter.get_node_text() instead. :help deprecated
This feature will be removed in Nvim version 0.10
2023-04-05T11:17:20  WARN stack traceback:
        ...im-macos/share/nvim/runtime/lua/vim/treesitter/query.lua:274: in function 'get_node_text'
        .../.local/share/nvim/lazy/yaml.nvim/lua/yaml_nvim/pair.lua:67: in function 'get_keys'
        .../.local/share/nvim/lazy/yaml.nvim/lua/yaml_nvim/pair.lua:89: in function 'parse'
        .../.local/share/nvim/lazy/yaml.nvim/lua/yaml_nvim/init.lua:59: in function 'func'
        .../.local/share/nvim/lazy/yaml.nvim/lua/yaml_nvim/init.lua:27: in function 'assure_yaml_filetype'
        .../.local/share/nvim/lazy/yaml.nvim/lua/yaml_nvim/init.lua:92: in function 'yank_key'
        [string ":lua"]:1: in main chunk

```

Also before this function was deprecated, the yank feature didn't work.

Thanks!

**Comment by mosheavni** [comment] 2023-04-05 16:51
> Can you clarify if you mean Vim/Neovim's generic _yank_ feature, or the `:YAMLYank` command?

Yes sorry I was about to paste the ex-command but forgot hehe
I meant `:YAMLYankKey`

**Comment by cuducos** [comment] 2023-04-05 19:40
No problem! It happens : )

I cannot reproduce it, though. Can you follow these steps to make sure we have some isolation?

1. Create a temporary directory (I'll call it `/tmp/yaml-plugin-test`)
1. Copy our minimum [`init.lua`](https://github.com/cuducos/yaml.nvim/blob/main/tests/init.lua) to `/tmp/yaml-plugin-test/.config/nvim/init.lua`
1. Add `install("https://github.com/cuducos/yaml.nvim", "/tmp/yaml.nvim")` to `/tmp/yaml-plugin-test/.config/nvim/init.lua`
1. Set Neovim to temporarily use this `init.lua` instead, you can do that with `export XDG_CONFIG_HOME=/tmp/yaml-plugin-test//config`

From there I opened `nvim some/file.yml` — I could `:YAMLYankKey` and then `p` to grab it back.

**Comment by mosheavni** [comment] 2023-04-06 16:39
> No problem! It happens : )
> 
> I cannot reproduce it, though. Can you follow these steps to make sure we have some isolation?
> 
> 1. Create a temporary directory (I'll call it `/tmp/yaml-plugin-test`)
> 2. Copy our minimum [`init.lua`](https://github.com/cuducos/yaml.nvim/blob/main/tests/init.lua) to `/tmp/yaml-plugin-test/.config/nvim/init.lua`
> 3. Add `install("https://github.com/cuducos/yaml.nvim", "/tmp/yaml.nvim")` to `/tmp/yaml-plugin-test/.config/nvim/init.lua`
> 4. Set Neovim to temporarily use this `init.lua` instead, you can do that with `export XDG_CONFIG_HOME=/tmp/yaml-plugin-test//config`
> 
> From there I opened `nvim some/file.yml` — I could `:YAMLYankKey` and then `p` to grab it back.

Actually the problem is because I'm using neovim nightly.
On stable it works fine.

**Comment by cuducos** [comment] 2023-04-06 17:42
> Actually the problem is because I'm using neovim nightly.

That's a really valuable heads-up! I'm gonna take a look and test on nightly then!
Don't wanna break the UX when they release : )
Thank you so much 💜

**Comment by cuducos** [comment] 2023-04-06 21:19
@mosheavni if you can, would you test [this branch](https://github.com/cuducos/yaml.nvim/tree/nightly-nvim) on nightly?

**Comment by mosheavni** [comment] 2023-04-07 14:09
> this branch

it's working but prompting:

```
vim.treesitter.query.get_node_text() is deprecated, use vim.treesitter.get_node_text() instead. :help deprecated
This feature will be removed in Nvim version 0.10
```

I guess these should be changed:
https://github.com/cuducos/yaml.nvim/blob/a17281607d1a09c41f1f74dea269564a5fdace3f/lua/yaml_nvim/pair.lua#L31
https://github.com/cuducos/yaml.nvim/blob/a17281607d1a09c41f1f74dea269564a5fdace3f/lua/yaml_nvim/pair.lua#L67

Thanks for your hard work!

**Comment by cuducos** [comment] 2023-04-07 16:11
Good point. As soon as I can get `:TSInstall yaml` to [work on the CI I](https://github.com/cuducos/yaml.nvim/actions/runs/4639546663/jobs/8210520299#step:5:26) merged it.

**Comment by mosheavni** [comment] 2023-04-07 16:50
> TSInstall yaml

how about:

```
nvim --headless --noplugin -u tests/init.lua -c "TSInstall yaml | PlenaryBustedDirectory tests/yaml_nvim { minimal_init = 'tests/init.lua' }"
```

**Closed as completed** 2023-04-11 18:58 UTC
Labels: bug
